# Goal
std_skills/Meta meta

# name of the pre-recorded motion to replay.
#
# if 'name' is empty or invalid, the skill should return immediately,
# with the list of available motions (see the Result section below)
string name

# if true, do not run motion planning before executing the motion
# -> might lead to collision!
bool unsafe

---
# Result
std_skills/Result result

# if 'name' is empty or invalid, the action should return immediately
# with the list of 'available_motions'.
string[] available_motions
---
# Feedback
std_skills/Feedback feedback
